apiVersion: v1
kind: Service
metadata:
  annotations:
    io.k8s.description: Alpine Node S2I Builder
    io.k8s.display-name: alien6/teachable-machine
    maintainer: Alien6 <contact@alien6.com>
    summary: Platform for building and running node applications
    version: "1"
  creationTimestamp: null
  labels:
    io.kompose.service: teachable-machine
  name: teachable-machine
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: teachable-machine
status:
  loadBalancer: {}
